### ISSUE TITLE
nice trojan kid

### ISSUE THREAD

**Issue by Jaska11vv** [shunf4/proxychains-windows#50] opened 2024-01-10 17:22 UTC
trojan detected
![deject1](https://github.com/shunf4/proxychains-windows/assets/156227492/1bb30ae7-d40e-4f16-85ad-62b5c03c4600)
![deject2](https://github.com/shunf4/proxychains-windows/assets/156227492/891d44bf-dfbd-4e1b-b8cd-caa4d657cbcb)
![deject3](https://github.com/shunf4/proxychains-windows/assets/156227492/56d76f10-5e04-49ea-bca3-a2b446f88fff)

hi, this program might contact a virus, i runned the 32bit version and my pc got fucked :D. BTW pretty shitty code for the virus...

"time to get fucked, fuck it lets go nuts" ::DD cringe shit 11 yo kid

**Comment by shunf4** [comment] 2024-01-14 07:47
It's a duplicate of https://github.com/shunf4/proxychains-windows/issues/19 which won't be fixed.

**Closed as not planned** 2024-01-14 07:48 UTC
